#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.11"
# dependencies = ["anthropic>=0.28", "numpy>=1.24", "zstandard>=0.22"]
# ///
"""
Independent LLM Annotation + Cohen's Kappa for farscry corpus.

Addresses @arromber concern #1: "O AER foi decidido por você mesmo."

This script uses Claude as an independent second annotator to label each
action in the corpus as SF (silent failure) or AE (action effect), then
computes Cohen's kappa between farscry's pHash-based labels and Claude's
vision-based labels.

A kappa > 0.6 indicates substantial agreement and validates the metric.
A kappa < 0.4 indicates the metric is unreliable.

Usage:
    ANTHROPIC_API_KEY=sk-... uv run spike/annotate_corpus.py \\
        --vasf-dir /path/to/sessions \\
        --failed-txt /path/to/failed_sessions.txt \\
        --output annotations.json

The --vasf-dir should contain .vasf files generated by farscry.
If --failed-txt is provided, sessions listed there are treated as failed tasks.

Format of failed_sessions.txt (one filename per line, no path):
    task_001.vasf
    task_007.vasf
    ...

Output JSON structure:
    {
      "kappa": 0.71,
      "kappa_interpretation": "substantial",
      "n_actions_annotated": 89,
      "farscry_sf": 32,
      "llm_sf": 28,
      "agreement": 0.84,
      "confusion_matrix": { "TP": 26, "FP": 2, "FN": 6, "TN": 55 },
      "sessions": [ ... ]
    }
"""

import argparse
import json
import os
import struct
import sys
from dataclasses import dataclass, asdict
from pathlib import Path
from typing import Optional

import anthropic
import numpy as np


# --- VASF binary format reader ---
# Matches farscry's VasfFile format in vasf.rs (format version 2)
#
# File header (22 bytes):
#   4 bytes  magic = b"VASF"
#   2 bytes  version (u16 LE)
#   4 bytes  frame_count (u32 LE)
#   8 bytes  created_at (i64 LE)
#   4 bytes  total_input (u32 LE)
#
# Frame (no frame_type byte — action markers identified by vasp content):
#   8 bytes  state_id (u64 LE)
#   8 bytes  timestamp (i64 LE)
#   4 bytes  vasp_len (u32 LE)
#   N bytes  vasp_data (zstd compressed)
#   4 bytes  delta_len (u32 LE)
#   M bytes  delta_data (zstd compressed, may be 0)
#
# Action marker: frame whose decompressed vasp_data starts with b"action_marker\n"

import zstandard as zstd

VASF_MAGIC = b"VASF"
ACTION_MARKER_PREFIX = "action_marker"

_dctx = zstd.ZstdDecompressor()


def _decompress(data: bytes) -> bytes:
    if not data:
        return b""
    try:
        return _dctx.stream_reader(data).read()
    except Exception:
        return b""


@dataclass
class VasfFrame:
    state_id: int  # 64-bit pHash (0 for action markers)
    vasp_text: str


def read_vasf(path: Path) -> list[VasfFrame]:
    """Parse a VASF binary file. Returns list of frames."""
    frames = []
    with open(path, "rb") as f:
        magic = f.read(4)
        if magic != VASF_MAGIC:
            raise ValueError(f"Not a VASF file: {path}")

        _version = struct.unpack("<H", f.read(2))[0]
        frame_count = struct.unpack("<I", f.read(4))[0]
        _created_at = struct.unpack("<q", f.read(8))[0]
        _total_input = struct.unpack("<I", f.read(4))[0]

        for _ in range(frame_count):
            state_id = struct.unpack("<Q", f.read(8))[0]
            _timestamp = struct.unpack("<q", f.read(8))[0]
            vasp_len = struct.unpack("<I", f.read(4))[0]
            vasp_data = _decompress(f.read(vasp_len)) if vasp_len > 0 else b""
            delta_len = struct.unpack("<I", f.read(4))[0]
            if delta_len > 0:
                f.read(delta_len)
            frames.append(VasfFrame(
                state_id=state_id,
                vasp_text=vasp_data.decode("utf-8", errors="replace"),
            ))

    return frames


def is_action_marker(frame: VasfFrame) -> bool:
    return frame.vasp_text.startswith(ACTION_MARKER_PREFIX)


def extract_vasf_field(text: str, field: str) -> str:
    for line in text.splitlines():
        if line.startswith(field):
            return line[len(field):].strip().strip('"')
    return ""


# --- farscry label extraction ---

@dataclass
class ActionLabel:
    action_index: int
    state_id_before: int
    state_id_after: int
    vasp_before: str
    vasp_after: str
    farscry_label: str  # "SF" or "AE" or "UNKNOWN"
    llm_label: Optional[str] = None
    llm_reasoning: Optional[str] = None


def extract_actions(frames: list[VasfFrame]) -> list[ActionLabel]:
    """Extract per-action labels from a VASF file using farscry's exact logic.
    Action markers have state_id=0 and vasp_text starting with 'action_marker'.
    The SF/AE label is determined by comparing state_id of the nearest non-marker
    frames before and after the marker.
    """
    marker_indices = [i for i, f in enumerate(frames) if is_action_marker(f)]
    actions = []

    for idx, midx in enumerate(marker_indices):
        before_frame = next(
            (frames[i] for i in range(midx - 1, -1, -1) if not is_action_marker(frames[i])),
            None
        )
        after_frame = next(
            (frames[i] for i in range(midx + 1, len(frames)) if not is_action_marker(frames[i])),
            None
        )

        if before_frame is None or after_frame is None:
            continue

        same = (before_frame.state_id == after_frame.state_id)
        label = "SF" if same else "AE"

        actions.append(ActionLabel(
            action_index=idx,
            state_id_before=before_frame.state_id,
            state_id_after=after_frame.state_id,
            vasp_before=before_frame.vasp_text,
            vasp_after=after_frame.vasp_text,
            farscry_label=label,
        ))

    return actions


# --- LLM annotation ---

ANNOTATION_PROMPT = """You are annotating a computer-use agent corpus to validate silent failure detection.

A "Silent Failure" (SF) means: the agent took an action (click, type, keypress), 
but the screen did not change. The action had no visible effect.

An "Action Effect" (AE) means: the action visibly changed the screen.

You will be shown the visual state BEFORE and AFTER an agent action, described
in VASP format (structured screen descriptions from farscry).

Classify the action as:
- SF: Silent Failure — screen did not meaningfully change
- AE: Action Effect — screen meaningfully changed

Respond with exactly this JSON format:
{
  "label": "SF" or "AE",
  "confidence": 0.0-1.0,
  "reasoning": "one sentence explanation"
}

State ID before: {state_id_before}
State ID after:  {state_id_after}

=== SCREEN BEFORE ACTION ===
{vasp_before}

=== SCREEN AFTER ACTION ===
{vasp_after}

Note: If state IDs are identical, the screen is bitwise identical per pHash.
Even with identical state IDs, use the VASP context to double-check your label."""


def annotate_with_llm(client: anthropic.Anthropic, action: ActionLabel, 
                       model: str = "claude-3-5-haiku-20241022") -> tuple[str, str]:
    """Call Claude to annotate a single action. Returns (label, reasoning)."""
    prompt = ANNOTATION_PROMPT.format(
        state_id_before=hex(action.state_id_before),
        state_id_after=hex(action.state_id_after),
        vasp_before=action.vasp_before[:800] if action.vasp_before else "(empty)",
        vasp_after=action.vasp_after[:800] if action.vasp_after else "(empty)",
    )

    response = client.messages.create(
        model=model,
        max_tokens=256,
        messages=[{"role": "user", "content": prompt}],
    )

    text = response.content[0].text.strip()
    try:
        parsed = json.loads(text)
        label = parsed.get("label", "UNKNOWN").upper()
        if label not in ("SF", "AE"):
            label = "UNKNOWN"
        reasoning = parsed.get("reasoning", "")
    except json.JSONDecodeError:
        if "SF" in text.upper() and "AE" not in text.upper():
            label, reasoning = "SF", text[:100]
        elif "AE" in text.upper():
            label, reasoning = "AE", text[:100]
        else:
            label, reasoning = "UNKNOWN", text[:100]

    return label, reasoning


# --- Cohen's Kappa ---

def cohens_kappa(farscry_labels: list[str], llm_labels: list[str]) -> dict:
    """
    Compute Cohen's kappa between two annotators.
    Both label lists must have the same length with values "SF" or "AE".
    """
    assert len(farscry_labels) == len(llm_labels)
    n = len(farscry_labels)
    if n == 0:
        return {"kappa": 0.0, "n": 0}

    # Confusion matrix treating SF=positive, AE=negative
    tp = sum(1 for f, l in zip(farscry_labels, llm_labels) if f == "SF" and l == "SF")
    fp = sum(1 for f, l in zip(farscry_labels, llm_labels) if f == "AE" and l == "SF")
    fn = sum(1 for f, l in zip(farscry_labels, llm_labels) if f == "SF" and l == "AE")
    tn = sum(1 for f, l in zip(farscry_labels, llm_labels) if f == "AE" and l == "AE")

    po = (tp + tn) / n  # observed agreement

    # Expected agreement
    p_sf_farscry = (tp + fn) / n
    p_sf_llm = (tp + fp) / n
    p_ae_farscry = (fp + tn) / n
    p_ae_llm = (fn + tn) / n
    pe = p_sf_farscry * p_sf_llm + p_ae_farscry * p_ae_llm

    kappa = (po - pe) / (1 - pe) if pe < 1.0 else 1.0

    def interpret(k: float) -> str:
        if k >= 0.80: return "almost perfect"
        if k >= 0.60: return "substantial"
        if k >= 0.40: return "moderate"
        if k >= 0.20: return "fair"
        return "slight or poor"

    return {
        "kappa": round(kappa, 4),
        "kappa_interpretation": interpret(kappa),
        "observed_agreement": round(po, 4),
        "expected_agreement": round(pe, 4),
        "n": n,
        "confusion_matrix": {"TP": tp, "FP": fp, "FN": fn, "TN": tn},
    }


# --- Main ---

def main():
    parser = argparse.ArgumentParser(description="Independent LLM annotation + Cohen's kappa")
    parser.add_argument("--vasf-dir", type=Path, required=True,
                        help="Directory containing .vasf files")
    parser.add_argument("--failed-txt", type=Path, default=None,
                        help="File listing failed session filenames (one per line)")
    parser.add_argument("--output", type=Path, default=Path("annotations.json"))
    parser.add_argument("--model", default="claude-3-5-haiku-20241022",
                        help="Claude model for annotation")
    parser.add_argument("--dry-run", action="store_true",
                        help="Parse VASFs and show stats without calling Claude API")
    parser.add_argument("--max-actions", type=int, default=None,
                        help="Limit total actions annotated (for cost control)")
    args = parser.parse_args()

    vasf_dir = args.vasf_dir
    if not vasf_dir.is_dir():
        print(f"ERROR: {vasf_dir} is not a directory", file=sys.stderr)
        sys.exit(1)

    vasf_files = sorted(vasf_dir.glob("*.vasf"))
    if not vasf_files:
        print(f"ERROR: no .vasf files in {vasf_dir}", file=sys.stderr)
        sys.exit(1)

    print(f"Found {len(vasf_files)} VASF files in {vasf_dir}")

    failed_names: set[str] = set()
    if args.failed_txt and args.failed_txt.exists():
        failed_names = {l.strip() for l in args.failed_txt.read_text().splitlines() if l.strip()}
        print(f"Loaded {len(failed_names)} failed session names from {args.failed_txt}")

    all_actions: list[tuple[str, ActionLabel]] = []  # (session_name, action)
    sessions_meta = []

    for vf in vasf_files:
        try:
            frames = read_vasf(vf)
        except Exception as e:
            print(f"  WARN: could not read {vf.name}: {e}", file=sys.stderr)
            continue

        actions = extract_actions(frames)
        sf_count = sum(1 for a in actions if a.farscry_label == "SF")
        ae_count = sum(1 for a in actions if a.farscry_label == "AE")
        is_failed = vf.name in failed_names
        print(f"  {vf.name}: {len(actions)} actions  SF={sf_count}  AE={ae_count}"
              f"  {'[FAILED]' if is_failed else '[OK]'}")

        sessions_meta.append({
            "filename": vf.name,
            "n_actions": len(actions),
            "sf_count": sf_count,
            "ae_count": ae_count,
            "is_failed": is_failed,
        })
        for action in actions:
            all_actions.append((vf.name, action))

    print(f"\nTotal actions: {len(all_actions)}")
    print(f"farscry SF labels: {sum(1 for _, a in all_actions if a.farscry_label == 'SF')}")
    print(f"farscry AE labels: {sum(1 for _, a in all_actions if a.farscry_label == 'AE')}")

    if args.dry_run:
        print("\n[dry-run] No API calls made. Re-run without --dry-run to annotate.")
        return

    api_key = os.environ.get("ANTHROPIC_API_KEY")
    if not api_key:
        print("ERROR: ANTHROPIC_API_KEY not set", file=sys.stderr)
        sys.exit(1)

    client = anthropic.Anthropic(api_key=api_key)

    actions_to_annotate = all_actions
    if args.max_actions:
        actions_to_annotate = all_actions[:args.max_actions]
        print(f"\nLimiting to {args.max_actions} actions (--max-actions)")

    print(f"\nAnnotating {len(actions_to_annotate)} actions with {args.model}...")
    print("Estimated cost: ~${:.3f} (claude-3-5-haiku @ $0.80/MTok input)".format(
        len(actions_to_annotate) * 600 / 1_000_000 * 0.80
    ))

    annotated: list[tuple[str, ActionLabel]] = []
    for i, (session_name, action) in enumerate(actions_to_annotate, 1):
        try:
            llm_label, reasoning = annotate_with_llm(client, action, model=args.model)
            action.llm_label = llm_label
            action.llm_reasoning = reasoning
            annotated.append((session_name, action))
            status = "✓" if llm_label == action.farscry_label else "✗"
            print(f"  [{i:3}/{len(actions_to_annotate)}] {session_name} action {action.action_index}: "
                  f"farscry={action.farscry_label} llm={llm_label} {status}")
        except Exception as e:
            print(f"  [{i:3}/{len(actions_to_annotate)}] ERROR: {e}", file=sys.stderr)

    # Filter to actions where both annotators gave SF/AE
    valid = [(s, a) for s, a in annotated
             if a.farscry_label in ("SF", "AE") and a.llm_label in ("SF", "AE")]

    farscry_labels = [a.farscry_label for _, a in valid]
    llm_labels = [a.llm_label for _, a in valid]

    kappa_result = cohens_kappa(farscry_labels, llm_labels)

    print(f"\n{'='*55}")
    print(f"COHEN'S KAPPA RESULTS")
    print(f"{'='*55}")
    print(f"  κ = {kappa_result['kappa']:.4f}  ({kappa_result['kappa_interpretation']})")
    print(f"  Observed agreement:  {kappa_result['observed_agreement']:.1%}")
    print(f"  Expected agreement:  {kappa_result['expected_agreement']:.1%}")
    print(f"  N (actions):         {kappa_result['n']}")
    cm = kappa_result["confusion_matrix"]
    print(f"  Confusion matrix:")
    print(f"    farscry=SF, llm=SF (TP): {cm['TP']}")
    print(f"    farscry=AE, llm=SF (FP): {cm['FP']}  ← farscry says AE, LLM disagrees")
    print(f"    farscry=SF, llm=AE (FN): {cm['FN']}  ← farscry says SF, LLM disagrees")
    print(f"    farscry=AE, llm=AE (TN): {cm['TN']}")

    if kappa_result["kappa"] >= 0.6:
        print(f"\n  ✓ κ ≥ 0.6: agreement is substantial — metric is valid for paper")
    elif kappa_result["kappa"] >= 0.4:
        print(f"\n  ⚠ κ 0.4–0.6: moderate agreement — investigate disagreements")
    else:
        print(f"\n  ✗ κ < 0.4: poor agreement — metric needs redesign")

    output = {
        **kappa_result,
        "model": args.model,
        "farscry_sf": sum(1 for l in farscry_labels if l == "SF"),
        "farscry_ae": sum(1 for l in farscry_labels if l == "AE"),
        "llm_sf": sum(1 for l in llm_labels if l == "SF"),
        "llm_ae": sum(1 for l in llm_labels if l == "AE"),
        "sessions": sessions_meta,
        "actions": [
            {
                "session": s,
                "action_index": a.action_index,
                "state_before": hex(a.state_id_before),
                "state_after": hex(a.state_id_after),
                "farscry": a.farscry_label,
                "llm": a.llm_label,
                "llm_reasoning": a.llm_reasoning,
                "agreement": a.farscry_label == a.llm_label,
            }
            for s, a in valid
        ],
    }

    args.output.write_text(json.dumps(output, indent=2))
    print(f"\nResults written to {args.output}")


if __name__ == "__main__":
    main()
